version: '3.7'
services: 
  sonarqube:
    image: sonarqube:7.1-alpine
    container_name: sonarqube
    ports:
      - 9000:9000
    volumes:
      - ./sonar.properties:/opt/sonarqube/conf/sonar.properties
      - ./temp/sonarqube/conf:/opt/sonarqube/conf
      - ./temp/sonarqube/data:/opt/sonarqube/data
      - ./temp/sonarqube/logs:/opt/sonarqube/logs
      - ./temp/sonarqube/extensions:/opt/sonarqube/extensions
    environment: 
      SONARQUBE_JDBC_USERNAME: "postgres"
      SONARQUBE_JDBC_PASSWORD: "admin@01sonarqube"
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres_db/sonar"
    depends_on: 
      - postgres_db
    command: bash -c 'while !</dev/tcp/postgres_db/5432; do sleep 1; done; ./bin/run.sh'

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - 5432:5432
    volumes:
      - ./temp/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "admin@01sonarqube"
      POSTGRES_DB: "sonar"
