version: '3.7'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    ports:
      - 8080:80
    volumes:
      - ./config:/etc/gitlab
      - ./log:/var/log/gitlab
      - ./data:/var/opt/data
    depends_on: 
      - postgres_db
    command: bash -c 'while !</dev/tcp/postgres_db/5432; do sleep 1; done; ./bin/run.sh'
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: "gitlabadmin"
      POSTGRES_DB: "gitlab"