version: '3.7'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
     - 5432:5432
    environment:
     POSTGRES_DB: artifactory
     POSTGRES_USER: artifactory
     POSTGRES_PASSWORD: password
     
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.11.6
    container_name: artifactory
    ports:
     - 8081:8081
    volumes:
     - ./temp/artifactory:/var/opt/jfrog/artifactory
    environment:
     DB_TYPE: postgresql
     DB_USER: artifactory
     DB_PASSWORD: password
     EXTRA_JAVA_OPTIONS: -Xmx1g
    depends_on:
     - postgresql
    command: bash -c 'while !</dev/tcp/postgresql/5432; do sleep 1; done; /entrypoint-artifactory.sh'